USE oper0341
SELECT l.PRF_PHYSN_UPIN, c.RFR_PHYSN_UPIN, count(*)
FROM carrier_claims c, carrier_lines l
WHERE c.DESY_SORT_KEY = l.DESY_SORT_KEY AND c.CLAIM_NO = l.CLAIM_NO AND c.CLM_THRU_DT = l.CLM_THRU_DT AND c.RFR_PHYSN_UPIN IS NOT NULL AND l.PRF_PHYSN_UPIN IS NOT NULL
GROUP BY l.PRF_PHYSN_UPIN,c.RFR_PHYSN_UPIN;

